apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: redis
    volumeMounts:
    - name: demoapp
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: demoapp
    secret:
      secretName: demosecret2
      items:
      - key: username
        path: username